### PR TITLE
Love 0.10.0+ support

### PR DESCRIPTION
**Pull request by Mystro256**
Mouse buttons were changed from "l" and "r" to 1 and 2 in love 0.10.0, so I used the variables lbutton and rbutton in main.lua, which are set according to the love version.

### CODE REVIEW

**Comment by Stabyourself** [comment]
I'm really sorry that I'm taking so long to reply to this; I'm really busy lately and haven't found the time to look at this. Rest assured that I still have this on my mind and will get to it as soon as possible!

**Comment by Stabyourself** [comment]
Thanks a ton, seems to be working great.

It doesn't seem like LÖVE will get reliable web support anytime soon, which is a shame. I'll have to see about how I want to update all the projects and clean them up..

**Comment by Mystro256** [comment]
No problem, I will see what I can be done about the others. I was looking into not tetris, I'll make a pull request and some comments over there.

**Comment by Mystro256** [comment]
A quick request: when you bump the version, can you also tag the release?
You can do it straight from github's website if you're not familiar with how to do it with git:
https://github.com/Stabyourself/orthorobot/releases

**Comment by Stabyourself** [comment]
Done. I hope I'm doing this right.
Also I apologize for Not Tetris 2's code in advance. It was my first game.

**Comment by Mystro256** [comment]
Looks good! Thanks!

**Comment by Mystro256** [comment]
Hold on, you changed the version to 2011 Stabyourself.net (**v1.2**) but tagged it as v1.1.1.

But I think you got the idea.
Thanks!

**Pull request merged**
